import type { CreateSignalInput, CreateSourceInput } from "./types";

// ─── SEED SIGNALS (all 27 rows from the risk matrix) ─────────────────────────
// Scores: businessImpact + legalComplexity + urgency (each 1–5)
// Critical = 13–15, High = 9–12, Medium = 5–8, Low = 1–4

export const SEED_SIGNALS: CreateSignalInput[] = [
  {
    title: "FTC Franchise Rule – FDD Disclosure Requirement",
    summary:
      "Offering or selling franchises in the U.S. requires a Franchise Disclosure Document containing 23 mandated categories, provided to prospective franchisees at least 14 calendar days before any payment or signing of a binding agreement.",
    sourceUrl: "https://www.ftc.gov/business-guidance/resources/amended-franchise-rule-faqs",
    sourceName: "FTC — Amended Franchise Rule FAQs",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    datePublished: "2024-10-30T00:00:00.000Z",
    jurisdiction: "US",
    category: "Franchise / Market Entry",
    businessImpactScore: 5, legalComplexityScore: 5, urgencyScore: 4, confidenceScore: 5,
    outsideCounselNeeded: true,
    notes: "16 C.F.R. § 436.2(f) and § 436.2(e). Must be sequenced before any U.S. franchise sales activity.",
  },
  {
    title: "State Franchise Registration – 14 Registration States",
    summary:
      "Before offering franchises in any of the 14 registration states (CA, HI, IL, IN, MD, MI, MN, NY, ND, RI, SD, VA, WA, WI), franchisors must file and receive state agency approval of the FDD. Review timelines typically 2–6 months per state.",
    sourceUrl: "https://www.ftc.gov/tips-advice/business-center/guidance/franchise-rule",
    sourceName: "FTC — State Franchise Laws",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    jurisdiction: "US",
    category: "Franchise / Market Entry",
    businessImpactScore: 5, legalComplexityScore: 5, urgencyScore: 4, confidenceScore: 5,
    outsideCounselNeeded: true,
    notes: "14 registration states — not '15+'. Filing before first franchise sales contact.",
  },
  {
    title: "UK Market Entry – London Cluster (H1 2026); Accelerated Expansion from Q3 2026",
    summary:
      "Burgermeister confirmed a cluster of four London locations for H1 2026, with accelerated expansion beginning Q3 2026. Food registration, employment contracts, lease execution, consumer protection, allergen compliance, and post-Brexit supply-chain clearance all apply from day one.",
    sourceUrl: "https://burgermeister.com/burgermeister-launches-in-the-uk-in-2026/",
    sourceName: "Burgermeister — UK Launch Announcement",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    datePublished: "2025-11-21T00:00:00.000Z",
    jurisdiction: "UK",
    category: "Franchise / Market Entry",
    businessImpactScore: 5, legalComplexityScore: 5, urgencyScore: 5, confidenceScore: 5,
    outsideCounselNeeded: true,
    notes: "CEO Robert Fügert: 'top three priority markets worldwide and springboard to the United States.'",
  },
  {
    title: "Joint-Venture Governance vs. Standard Franchise Structure",
    summary:
      "Burgermeister's Poland entry used a JV structure (Burgermeister Group sp. z o.o.), financed entirely by Burgermeister Group. JV governance creates distinct legal obligations vs. pure franchising: equity, profit-share, deadlock, exit rights, IP ownership, liability allocation.",
    sourceUrl: "https://burgermeister.com/burgermeister-goes-international-kick-off-in-poland-for-our-european-expansion/",
    sourceName: "Burgermeister — Poland JV Announcement",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    datePublished: "2025-08-05T00:00:00.000Z",
    jurisdiction: "Global",
    category: "Franchise / Market Entry",
    businessImpactScore: 5, legalComplexityScore: 5, urgencyScore: 4, confidenceScore: 5,
    outsideCounselNeeded: true,
    notes: "JV model likely replicated in UK and future markets. Not pure franchise.",
  },
  {
    title: "European Franchise Federation Code of Ethics – Voluntary Norms, Referenced in Disputes",
    summary:
      "The EFF Code is a voluntary self-regulatory instrument, not directly enforceable law. Courts and arbitrators in EU member states may reference it as evidence of industry norms in franchise relationship disputes.",
    sourceUrl: "https://www.eff-franchise.com/",
    sourceName: "European Franchise Federation",
    sourceTier: 2,
    dateFound: new Date().toISOString(),
    jurisdiction: "EU",
    category: "Franchise / Market Entry",
    businessImpactScore: 3, legalComplexityScore: 2, urgencyScore: 2, confidenceScore: 4,
    outsideCounselNeeded: false,
    notes: "Voluntary only — do not characterize as directly enforceable.",
  },
  {
    title: "Trademark Registration in All Target Markets",
    summary:
      "Marks must be registered in each target jurisdiction (UK, US, PL, CZ, NL, CH, UAE). Prior-use and first-to-register rules vary. Copycat concepts or squatted marks can block expansion.",
    sourceUrl: "https://www.uspto.gov/trademarks",
    sourceName: "USPTO — Trademark Basics",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Brand / IP Protection",
    businessImpactScore: 5, legalComplexityScore: 4, urgencyScore: 5, confidenceScore: 5,
    outsideCounselNeeded: true,
  },
  {
    title: "Trade Dress, Menu Name, and Berlin-Origin Story Protection",
    summary:
      "Burgermeister's visual identity, menu naming, 'Berlin cult favorite' positioning, Schlesisches Tor origin story, and product presentation may be protectable as trade dress or distinctive mark in expansion markets.",
    sourceUrl: "https://www.uspto.gov/trademarks",
    sourceName: "USPTO — Trademark Basics",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Brand / IP Protection",
    businessImpactScore: 4, legalComplexityScore: 4, urgencyScore: 4, confidenceScore: 4,
    outsideCounselNeeded: true,
  },
  {
    title: "Domain Names and Social Handles in Target Markets",
    summary:
      "Core domains and social handles in UK, US, PL, CZ, NL, CH, and UAE should be secured before brand announcement or market launch press.",
    sourceUrl: "https://burgermeister.com",
    sourceName: "Burgermeister — Brand Monitoring",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Brand / IP Protection",
    businessImpactScore: 3, legalComplexityScore: 2, urgencyScore: 3, confidenceScore: 4,
    outsideCounselNeeded: false,
  },
  {
    title: "EU–UK Food Import Clearance Under UK Border Target Operating Model (BTOM)",
    summary:
      "All locations supplied from central Berlin Tempelhof production. Irish beef patties (animal products) require health certification (BTOM Phase 1, effective 31 Jan. 2024) and physical SPS checks at Border Control Posts (Phase 2, effective 30 Apr. 2024). CHED notifications required via IPAFFS.",
    sourceUrl: "https://www.gov.uk/government/publications/the-border-target-operating-model-august-2023",
    sourceName: "UK Gov / APHA — BTOM Import Guidance",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    datePublished: "2024-01-31T00:00:00.000Z",
    jurisdiction: "UK",
    category: "Post-Brexit Supply Chain / Import Compliance",
    businessImpactScore: 5, legalComplexityScore: 5, urgencyScore: 5, confidenceScore: 5,
    outsideCounselNeeded: true,
    notes: "Phase 1: 31 Jan 2024 (health certs). Phase 2: 30 Apr 2024 (physical SPS checks). Beef patties = animal products = Phase 2.",
  },
  {
    title: "Lease Assignment, Change-of-Control, and JV/Franchise Lease Control",
    summary:
      "JV and franchise expansion requires enforceable lease-assignment rights and protections against landlord refusal when operators change. Change-of-control clauses can trigger landlord consent requirements.",
    sourceUrl: "https://burgermeister.com",
    sourceName: "Burgermeister — Expansion Intelligence",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Real Estate / Site Acquisition",
    businessImpactScore: 5, legalComplexityScore: 4, urgencyScore: 4, confidenceScore: 4,
    outsideCounselNeeded: true,
  },
  {
    title: "Permitting, Zoning, Signage, Buildout, and Food-Service Compliance Obligations",
    summary:
      "QSR locations require food-service permits, ventilation and grease-trap compliance, signage approval, and buildout standards that vary by jurisdiction. Ghost kitchen pre-launch model may have distinct permitting requirements.",
    sourceUrl: "https://burgermeister.com",
    sourceName: "Burgermeister — Expansion Intelligence",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Real Estate / Site Acquisition",
    businessImpactScore: 4, legalComplexityScore: 3, urgencyScore: 4, confidenceScore: 3,
    outsideCounselNeeded: true,
  },
  {
    title: "Food Business Registration – 28-Day Pre-Trading Requirement (UK)",
    summary:
      "Every UK food business must register with the local authority at least 28 days before trading under the Food Premises (Registration) Regulations 1991. Free, cannot be refused, but must be built into the launch sequence for each London location.",
    sourceUrl: "https://www.food.gov.uk/business-guidance/getting-ready-to-start-your-food-business",
    sourceName: "UK Food Standards Agency — Starting a Food Business",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    jurisdiction: "UK",
    category: "Food Compliance / Labeling",
    businessImpactScore: 5, legalComplexityScore: 3, urgencyScore: 5, confidenceScore: 5,
    outsideCounselNeeded: false,
    notes: "Food Premises (Registration) Regulations 1991, S.I. 1991/2825. Free and cannot be refused but timing is critical.",
  },
  {
    title: "Allergen Disclosure – Food Information Regulations 2014 and Natasha's Law (PPDS)",
    summary:
      "FIR 2014 requires allergen info for 14 major allergens in non-prepacked food before purchase. Natasha's Law (Oct. 2021) requires full ingredient and allergen labelling on PPDS items. Burgermeister's in-house baked and packaged cookies may trigger Natasha's Law independently.",
    sourceUrl: "https://www.food.gov.uk/business-guidance/allergen-guidance-for-food-businesses",
    sourceName: "UK Food Standards Agency — Allergen Guidance",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    datePublished: "2021-10-01T00:00:00.000Z",
    jurisdiction: "UK",
    category: "Food Compliance / Labeling",
    businessImpactScore: 5, legalComplexityScore: 4, urgencyScore: 5, confidenceScore: 5,
    outsideCounselNeeded: true,
    notes: "FIR 2014 S.I. 2014/1855. Natasha's Law S.I. 2019/1218. Cookies = likely PPDS items.",
  },
  {
    title: "Food Hygiene Rating Scheme – Voluntary in England; Mandatory in Wales/NI",
    summary:
      "Display is legally mandatory in Wales and Northern Ireland, but voluntary in England. London locations are in England. Ratings are publicly visible on FSA register regardless of display. FSA has previously proposed extending mandatory display to England.",
    sourceUrl: "https://www.food.gov.uk/safety-hygiene/food-hygiene-rating-scheme",
    sourceName: "UK Food Standards Agency — Hygiene Rating Scheme",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    jurisdiction: "UK",
    category: "Food Compliance / Labeling",
    businessImpactScore: 3, legalComplexityScore: 2, urgencyScore: 3, confidenceScore: 5,
    outsideCounselNeeded: false,
    notes: "Mandatory in Wales (S.I. 2013/418 (W.55)) and NI. Voluntary in England. London = England = voluntary.",
  },
  {
    title: "FDA Menu Labeling – 20-Location Chain Trigger (21 C.F.R. § 101.11)",
    summary:
      "FDA requires calorie and nutrition disclosure on menus for chain restaurants with 20 or more locations under the same name offering substantially the same menu items, regardless of franchise ownership type.",
    sourceUrl: "https://www.fda.gov/food/nutrition-food-labeling-and-critical-foods/menu-labeling-requirements",
    sourceName: "FDA — Menu Labeling Requirements",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    datePublished: "2018-05-07T00:00:00.000Z",
    jurisdiction: "US",
    category: "Food Compliance / Labeling",
    businessImpactScore: 4, legalComplexityScore: 3, urgencyScore: 3, confidenceScore: 5,
    outsideCounselNeeded: false,
    notes: "21 C.F.R. § 101.11. Compliance date May 7, 2018. Build into U.S. operating system before 20-location threshold.",
  },
  {
    title: "Supplier and Vendor Contract Framework – Central Production Model",
    summary:
      "All locations supplied from a single Berlin Tempelhof facility (Irish beef patties, Dutch fries, in-house buns, sauces, cookies). Enforceable supplier agreements covering quality standards, food safety, pricing controls, and cross-border supply logistics are required as scale increases.",
    sourceUrl: "https://burgermeister.com/german-burger-chain-succeeds-where-five-guys-failed/",
    sourceName: "Burgermeister — Supply Chain Operations",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    datePublished: "2025-12-03T00:00:00.000Z",
    jurisdiction: "Global",
    category: "Supply Chain / Quality Control",
    businessImpactScore: 4, legalComplexityScore: 4, urgencyScore: 4, confidenceScore: 4,
    outsideCounselNeeded: true,
  },
  {
    title: "Exclusivity and MFN Clauses in Delivery Platform Contracts",
    summary:
      "Burgermeister has an exclusive product partnership with Wolt (Woltmeister Burger). Platform contracts with Wolt, Uber Eats, and Lieferando may contain exclusivity restrictions or MFN pricing clauses that constrain brand flexibility and margins in new markets.",
    sourceUrl: "https://burgermeister.com",
    sourceName: "Burgermeister — Delivery Platform Intelligence",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Delivery Platforms",
    businessImpactScore: 5, legalComplexityScore: 4, urgencyScore: 4, confidenceScore: 4,
    outsideCounselNeeded: true,
    notes: "Woltmeister Burger = confirmed exclusive product. Wolt, Uber Eats, Lieferando all active partnerships.",
  },
  {
    title: "Customer Data Ownership and Access Rights in Platform Contracts",
    summary:
      "Delivery platforms aggregate customer order history, contact data, and behavioral data. Platform contracts often restrict brand access, limiting direct customer relationships, retention programs, and marketing analytics.",
    sourceUrl: "https://burgermeister.com",
    sourceName: "Burgermeister — Delivery Platform Intelligence",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Delivery Platforms",
    businessImpactScore: 5, legalComplexityScore: 4, urgencyScore: 4, confidenceScore: 4,
    outsideCounselNeeded: true,
  },
  {
    title: "Commission Rate Regulation and Platform Fee Developments",
    summary:
      "Multiple U.S. cities and EU jurisdictions have enacted or proposed commission caps on delivery platform fees. Regulatory developments can alter platform-negotiation leverage and unit economics.",
    sourceUrl: "https://burgermeister.com",
    sourceName: "Burgermeister — Delivery Platform Intelligence",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Delivery Platforms",
    businessImpactScore: 3, legalComplexityScore: 2, urgencyScore: 2, confidenceScore: 3,
    outsideCounselNeeded: false,
  },
  {
    title: "Wage, Hour, Working Time Regulations 1998 – 48hr Limit, Rest, Opt-Out Documentation",
    summary:
      "FLSA (U.S.), Working Time Regulations 1998 (UK) — 48-hour weekly maximum (reg. 4), 11-hour daily rest (reg. 10), four weeks' paid leave (reg. 13), written opt-out right with documentation requirements — and EU national equivalents all apply to QSR expansion.",
    sourceUrl: "https://www.legislation.gov.uk/uksi/1998/1833",
    sourceName: "UK legislation.gov.uk — Working Time Regulations 1998 S.I. 1998/1833",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Labor / Employment",
    businessImpactScore: 5, legalComplexityScore: 4, urgencyScore: 4, confidenceScore: 5,
    outsideCounselNeeded: true,
    notes: "Opt-out agreements: revocable on 7 days' notice minimum; require documentation. Common in UK hospitality.",
  },
  {
    title: "Joint-Employer Exposure – Reinstated 2020 NLRB Standard",
    summary:
      "2023 NLRB joint-employer rule vacated (E.D. Tex., Mar. 2024); NLRB reinstated 2020 standard (Mar. 2026). Current rule: substantial, direct, and immediate control over essential terms and conditions. Operational standards exercising de facto control over franchisee scheduling or wages remain at risk.",
    sourceUrl: "https://www.hklaw.com/en/insights/publications/2026/03/nlrb-withdraws-2023-joint-employer-rule",
    sourceName: "Holland & Knight — NLRB Withdraws 2023 Joint Employer Rule",
    sourceTier: 2,
    dateFound: new Date().toISOString(),
    datePublished: "2026-03-03T00:00:00.000Z",
    jurisdiction: "US",
    category: "Labor / Employment",
    businessImpactScore: 4, legalComplexityScore: 4, urgencyScore: 3, confidenceScore: 4,
    outsideCounselNeeded: true,
    notes: "2020 standard reinstated. Standard in flux across administrations — monitor.",
  },
  {
    title: "GDPR and UK GDPR – Data Processing Obligations and Fine Exposure",
    summary:
      "Customer loyalty data, delivery data, marketing analytics, and AI tools trigger GDPR obligations. Fines for the most serious violations: up to €20,000,000 or 4% of total worldwide annual turnover, whichever is higher. At €100M+ confirmed 2025 revenue, 4% = €4M+ potential exposure.",
    sourceUrl: "https://gdpr.eu/article-83-conditions-for-imposing-administrative-fines/",
    sourceName: "EU Regulation 2016/679 (GDPR) — Art. 83(5)",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    jurisdiction: "EU",
    category: "Data / AI / Privacy",
    businessImpactScore: 5, legalComplexityScore: 5, urgencyScore: 4, confidenceScore: 5,
    outsideCounselNeeded: true,
    notes: "4% of €100M+ = €4M+ fine exposure. Burgermeister loyalty app + delivery data both in scope.",
  },
  {
    title: "EU AI Act – General Application: 2 August 2026 (Seven Weeks Away)",
    summary:
      "EU AI Act (Reg. 2024/1689) entered into force 1 August 2024. General application — high-risk AI systems, transparency, enforcement — takes effect 2 August 2026. AI in hiring, scheduling, analytics, pricing, or marketing in EU markets must be classified. Digital Omnibus proposal may delay high-risk rules.",
    sourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",
    sourceName: "European Commission — EU AI Act",
    sourceTier: 1,
    dateFound: new Date().toISOString(),
    datePublished: "2024-08-01T00:00:00.000Z",
    jurisdiction: "EU",
    category: "Data / AI / Privacy",
    businessImpactScore: 5, legalComplexityScore: 5, urgencyScore: 5, confidenceScore: 5,
    outsideCounselNeeded: true,
    notes: "Seven weeks to general application date as of June 2026. Digital Omnibus delay proposal under consideration.",
  },
  {
    title: "Quality, Origin, and Sourcing Claims Substantiation",
    summary:
      "Claims about 100% Irish beef sourcing, Berlin origin, 'best burger' positioning, or sustainability credentials must be substantiated and compliant with local consumer protection law in each target market.",
    sourceUrl: "https://burgermeister.com",
    sourceName: "Burgermeister — Marketing Claims",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Advertising / Consumer Protection",
    businessImpactScore: 3, legalComplexityScore: 3, urgencyScore: 2, confidenceScore: 3,
    outsideCounselNeeded: false,
  },
  {
    title: "Legal Infrastructure Readiness for PE, M&A, and JV Processes",
    summary:
      "PE investors, acquirers, and JV partners require organized contracts, consistent franchise/JV documentation, IP ownership clarity, assignable leases, documented employment policies, and clean data practices.",
    sourceUrl: "https://burgermeister.com",
    sourceName: "Burgermeister — Investor Relations Intelligence",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "M&A / JV / Investor Diligence Readiness",
    businessImpactScore: 5, legalComplexityScore: 4, urgencyScore: 4, confidenceScore: 4,
    outsideCounselNeeded: true,
  },
  {
    title: "Food Safety, Labor, Supply Chain, and Brand Crisis Signal Monitoring",
    summary:
      "Food safety incidents, labor violations, delivery-platform disputes, and brand misuse can spread rapidly. Single-point-of-failure central supply chain amplifies risk of any production or import disruption.",
    sourceUrl: "https://burgermeister.com",
    sourceName: "Burgermeister — Crisis Monitoring",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    jurisdiction: "Global",
    category: "Crisis / Reputation Monitoring",
    businessImpactScore: 4, legalComplexityScore: 2, urgencyScore: 2, confidenceScore: 3,
    outsideCounselNeeded: false,
  },
  {
    title: "Premium QSR Competitor Expansion Monitoring",
    summary:
      "Five Guys, Shake Shack (18 UK locations; expanding to Manchester 2026), McDonald's premiumization, and local 'better burger' concepts are active in Burgermeister's target markets. CZ and NL have established premium QSR incumbents.",
    sourceUrl: "https://www.timeout.com/uk/news/shake-shack-is-opening-its-first-ever-restaurant-in-the-north-of-england-in-2026-120425",
    sourceName: "Time Out — Shake Shack UK Expansion 2026",
    sourceTier: 3,
    dateFound: new Date().toISOString(),
    datePublished: "2025-12-04T00:00:00.000Z",
    jurisdiction: "Global",
    category: "Competitor / Market Intelligence",
    businessImpactScore: 2, legalComplexityScore: 1, urgencyScore: 2, confidenceScore: 4,
    outsideCounselNeeded: false,
    notes: "Shake Shack: 18 UK locations as of 2026. Manchester expansion March 2026.",
  },
];

// ─── SEED SOURCES (17 primary sources) ───────────────────────────────────────

export const SEED_SOURCES: CreateSourceInput[] = [
  { name:"FTC — Franchise Rule 16 C.F.R. § 436",                  url:"https://www.ftc.gov/business-guidance/resources/amended-franchise-rule-faqs",            jurisdiction:"US",     category:"Franchise / Market Entry",                tier:1, updateFrequency:"monthly"  },
  { name:"FDA — Menu Labeling Requirements 21 C.F.R. § 101.11",   url:"https://www.fda.gov/food/nutrition-food-labeling-and-critical-foods/menu-labeling-requirements", jurisdiction:"US", category:"Food Compliance / Labeling",              tier:1, updateFrequency:"monthly"  },
  { name:"U.S. DOL — FLSA Restaurant Industry Guidance",           url:"https://www.dol.gov/agencies/whd/fact-sheets/2-flsa-restaurants",                                 jurisdiction:"US",     category:"Labor / Employment",                       tier:1, updateFrequency:"monthly"  },
  { name:"USPTO — Trademark Basics",                               url:"https://www.uspto.gov/trademarks",                                                        jurisdiction:"US",     category:"Brand / IP Protection",                   tier:1, updateFrequency:"monthly"  },
  { name:"UK FSA — Starting a Food Business (28-day registration)",url:"https://www.food.gov.uk/business-guidance/getting-ready-to-start-your-food-business",    jurisdiction:"UK",     category:"Food Compliance / Labeling",              tier:1, updateFrequency:"monthly"  },
  { name:"UK FSA — Allergen Guidance (FIR 2014 + Natasha's Law)",  url:"https://www.food.gov.uk/business-guidance/allergen-guidance-for-food-businesses",        jurisdiction:"UK",     category:"Food Compliance / Labeling",              tier:1, updateFrequency:"monthly"  },
  { name:"UK FSA — Food Hygiene Rating Scheme",                    url:"https://www.food.gov.uk/safety-hygiene/food-hygiene-rating-scheme",                      jurisdiction:"UK",     category:"Food Compliance / Labeling",              tier:1, updateFrequency:"monthly"  },
  { name:"UK Gov / APHA — BTOM Import Guidance",                   url:"https://www.gov.uk/government/publications/the-border-target-operating-model-august-2023", jurisdiction:"UK", category:"Post-Brexit Supply Chain / Import Compliance", tier:1, updateFrequency:"weekly" },
  { name:"UK legislation.gov.uk — Working Time Regulations 1998",  url:"https://www.legislation.gov.uk/uksi/1998/1833",                                           jurisdiction:"UK",     category:"Labor / Employment",                       tier:1, updateFrequency:"monthly"  },
  { name:"UK ICO — Data Protection Guidance",                      url:"https://ico.org.uk/for-organisations",                                                    jurisdiction:"UK",     category:"Data / AI / Privacy",                      tier:1, updateFrequency:"weekly"   },
  { name:"EU — GDPR Regulation 2016/679 Art. 83",                  url:"https://gdpr.eu/article-83-conditions-for-imposing-administrative-fines/",                jurisdiction:"EU",     category:"Data / AI / Privacy",                      tier:1, updateFrequency:"monthly"  },
  { name:"European Commission — EU AI Act Reg. 2024/1689",         url:"https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",              jurisdiction:"EU",     category:"Data / AI / Privacy",                      tier:1, updateFrequency:"weekly"   },
  { name:"EU — EUR-Lex (GDPR, AI Act, EFSA, consumer protection)", url:"https://eur-lex.europa.eu/homepage.html",                                                 jurisdiction:"EU",     category:"Franchise / Market Entry",                tier:1, updateFrequency:"weekly"   },
  { name:"European Franchise Federation — Code of Ethics",         url:"https://www.eff-franchise.com/",                                                          jurisdiction:"EU",     category:"Franchise / Market Entry",                tier:2, updateFrequency:"monthly"  },
  { name:"ACC — In-House Counsel Resources",                       url:"https://www.acc.com/resource-library",                                                    jurisdiction:"Global", category:"M&A / JV / Investor Diligence Readiness", tier:2, updateFrequency:"weekly"   },
  { name:"Burgermeister.com — News and Press Releases",            url:"https://burgermeister.com/news/",                                                         jurisdiction:"Global", category:"Competitor / Market Intelligence",          tier:3, updateFrequency:"daily",
    notes:"Primary source for expansion announcements, operational reports, franchise partner calls, UK/US market entry updates. Monitor daily." },
  { name:"Nation's Restaurant News",                               url:"https://www.nrn.com",                                                                     jurisdiction:"US",     category:"Competitor / Market Intelligence",          tier:3, updateFrequency:"daily"    },
];
